# Generated by Django 4.0.4 on 2022-05-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_categories_alter_product_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='shop',
            name='street',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
