# Generated by Django 4.0.4 on 2022-05-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_shop_city_alter_shop_street'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prod',
        ),
    ]
